-- Remove the unused `Site.risk` classification column.
--
-- Site.risk was a per-site HIGH/MEDIUM/LOW tag that is no longer surfaced
-- anywhere in the product (the Settings → Sites list + modal, the login site
-- picker, the site-filter banner and the governance readiness heatmap all
-- dropped it). The dashboard/governance "risk" surfaces derive their signal
-- from CAPA / system / finding severity, NOT from this column.
--
-- Portable single-statement DROP COLUMN — valid on PostgreSQL (CI + prod) and
-- SQLite ≥ 3.35 (dev), so `migrate deploy` applies it cleanly on both.
ALTER TABLE "Site" DROP COLUMN "risk";
