"use client";

/**
 * AIBadge — the ONE provenance marker for AI-generated content.
 *
 * Two jobs, and the second one is why this exists:
 *   1. Mark AI-generated output consistently ("AI Generated").
 *   2. Make a DEMO-DATA fallback visually distinct from a real AI result.
 *
 * Every AI gateway in this app degrades to a deterministic fixture when the
 * backend errors. Those fixtures render identically to real output unless the
 * surface says otherwise — which is how fabricated CAPA references and
 * fabricated drift alerts reached users. So `source="mock"` deliberately drops
 * the indigo accent and renders grey: demo data must never wear the AI colour.
 *
 * Styling lives in index.css (.ai-badge / .ai-badge-demo) — never inline.
 */

import { Sparkles, FlaskConical } from "lucide-react";
import clsx from "clsx";

export interface AIBadgeProps {
  /**
   * Provenance of the content this badge annotates.
   *   "backend" → a real AI call produced it.
   *   "mock"    → the deterministic demo fixture produced it (backend failed).
   */
  source?: "backend" | "mock";
  /** Override the label. Defaults to "AI Generated" / "Demo data". */
  label?: string;
  className?: string;
}

export function AIBadge({ source = "backend", label, className }: AIBadgeProps) {
  const isMock = source === "mock";
  const Icon = isMock ? FlaskConical : Sparkles;
  const text = label ?? (isMock ? "Demo data" : "AI Generated");

  return (
    <span
      className={clsx("ai-badge", isMock && "ai-badge-demo", className)}
      // Screen-reader parity: the icon is decorative, so state the provenance.
      title={
        isMock
          ? "Demo data — the AI backend was unavailable, so this is fixture content."
          : "Generated by AI. Review before use."
      }
    >
      <Icon aria-hidden="true" />
      {text}
    </span>
  );
}
